CREATE TRIGGER T_Update_GI_ITEM_ATRIB 
ON GI_ITEM_ATRIB
AFTER
UPDATE
AS
insert into GI_ITEM_ATRIB_TRIGGER
select OP_ITEM_PROD, CD_ATRIBUTO, AN_VALOR, getdate(), 'U' from Inserted


CREATE TRIGGER T_Insert_GI_ITEM_ATRIB 
ON GI_ITEM_ATRIB
AFTER
INSERT
AS
insert into GI_ITEM_ATRIB_TRIGGER
select OP_ITEM_PROD, CD_ATRIBUTO, AN_VALOR, getdate(), 'I' from Inserted


CREATE TRIGGER T_Delete_GI_ITEM_ATRIB 
ON GI_ITEM_ATRIB
AFTER
DELETE
AS
insert into GI_ITEM_ATRIB_TRIGGER
select OP_ITEM_PROD, CD_ATRIBUTO, AN_VALOR, getdate(), 'D' from Deleted


--Apagar triggers
DROP TRIGGER T_Update_GI_ITEM_ATRIB
DROP TRIGGER T_Insert_GI_ITEM_ATRIB
DROP TRIGGER T_Delete_GI_ITEM_ATRIB
