CREATE USER usuario
  IDENTIFIED BY  usuario
  DEFAULT TABLESPACE usuario
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
 
 GRANT CONNECT TO usuario; 
 GRANT RESOURCE TO usuario;
 GRANT UNLIMITED TABLESPACE TO usuario;
 GRANT UNLIMITED TABLESPACE TO TS_usuario