---
- hosts: all
  tasks:
    - name: 'Instala o PHP5'
      apt:
        name: php5
        state: latest
      become: yes
    - name: 'Instala o Apache2'
      apt: 
        name: apache2
        state:lastest
      became: yes
    - name: 'Instala o Apache2'
      apt: 
        name: libapache2-mod-php5
        state:lastest
      became: yes